build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy
  - activate test-environment
  - pip install nose-exclude
  - pip install -r requirements.txt

test_script:
  - nosetests -s -v --exclude-dir=mlens/externals --exclude-dir=mlens/visualization
