doc-warnings: yes

ignore-paths:
  - doc/examples
  - mlens/externals

ignore-patterns:
    - ^example/doc_.*\.py$
    - __init__.py

pylint:
  disable:
    - too-many-local-variables
    - too-many-arguments
