doc-warnings: yes

ignore-paths:
  - docs/
  - mlens/externals
  - dev/
  - benchmarks/

ignore-patterns:
    - ^example/doc_.*\.py$
    - __init__.py

pylint:
  disable:
    - too-many-local-variables
    - too-many-arguments
    - access-to-a-protected-member-of-a-client-class
    - redefining-built-in
